### ISSUE TITLE
Compatibility with unified v10

### ISSUE THREAD

**Issue by schickling** [leafac/rehype-shiki#2]
[Unified 10.x](https://github.com/unifiedjs/unified/releases/tag/10.0.0) has been released a few weeks ago which seems to have contained a few breaking changes which broke compatibility with `rehype-shiki`. 

Would be great if this package could be upgraded soon. Thanks a ton! 💯

**Comment by leafac** [comment]
Thanks for reaching out. I’ll get to this soon…

**Comment by schickling** [comment]
@leafac did you get a chance to take a look at this yet? Seems like this would be useful for quite a lot of folks :)

**Comment by leafac** [comment]
Fixed on 2.0.1.

**Comment by schickling** [comment]
Thanks a lot @leafac
