### ISSUE TITLE
Build error in Vercel

### ISSUE THREAD

**Issue by re-taro** [leafac/rehype-shiki#4]
Hello, I have some question.

When I use your so awesome unified plugin.

I've encountered this error

```
UnhandledSchemeError: Reading from "node:assert/strict" is not handled by plugins (Unhandled scheme).
```

What should I do?

**Comment by leafac** [comment]
Hi @re-taro,

Thanks for reaching out.

@leafac/rehype-shiki only works with ESM, and it seems like your project hasn’t transitioned yet. You may learn how to do that here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

In any case, it seems like you solved the problem already, given that you closed the issue. What was the solution?
